# -*- coding: utf-8 -*-
"""DP project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/141DUc_6mR1WW9rQummGKCbohgQlEPJaN
"""

#  GoldBod Case Study: Stochastic Finite-Horizon DP
#  2026 Forward Schedule — JP Morgan Gold Price Forecasts
#
#  Purpose: optimal procurement schedule for 2026 using
#  JP Morgan quarterly gold price forecasts and assumed
#  exchange rate range U[10.50, 12.50] GHS/USD.
#
#  Key corrections from original 2026 code:
#    1. Buy cost: (gold * fx * C_TROY) / K_CONV  (not * C_TROY)
#    2. lambda_arr: period-specific, not scalar
#    3. p_sell_arr: equals lambda_arr (Option A — buy cost proxy)
#       since no 2026 actual transfer prices available
#    4. DP solver and forward sim use array parameters
#    5. Stochastic loop computes lambda_xi per scenario
#    6. Parameters: FX [10.50,12.50], threshold 11.00,
#       Q=127,000 kg, PHI=5.0, weights from sensitivity
#
#  Assumption (p_sell):
#    Since no 2026 transfer price data exists, p_sell_t = lambda_t
#    (buy cost used as proxy for BoG transfer price).
#    This is conservative — the actual transfer price in 2025
#    was ~4.76x the buy cost. The discrepancy measure therefore
#    reflects cost-based supply performance rather than
#    revenue-based performance.
#
#  Outputs saved to Google Drive OUTPUT_DIR.
# ============================================================

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import time
import warnings
warnings.filterwarnings('ignore')

# ─────────────────────────────────────────────────────────────
# GOOGLE DRIVE SETUP
# ─────────────────────────────────────────────────────────────
from google.colab import drive
drive.mount('/content/drive')

DRIVE_FOLDER = 'GoldBod_DP_2026'
OUTPUT_DIR   = f'/content/drive/MyDrive/{DRIVE_FOLDER}/'
os.makedirs(OUTPUT_DIR, exist_ok=True)
print(f'Output directory: {OUTPUT_DIR}\n')

# ─────────────────────────────────────────────────────────────
# SECTION 0 — Parameters
# ─────────────────────────────────────────────────────────────

T        = 52        # 52 weekly periods for 2026
periods  = range(T)
S0       = 0.0

C_TROY   = 32.1507   # troy oz per kg
K_CONV   = 4.186     # Ghana Pounds per troy oz (GoldBod scale)
# Correct buy cost per kg: (gold_usd * fx * C_TROY) / K_CONV

# JP Morgan 2026 quarterly gold price forecasts (USD/oz)
JP_QUARTERLY = [4_440, 4_655, 4_860, 5_055]

# Exchange rate: U[FX_LOW, FX_HIGH] GHS/USD
FX_LOW       = 10.50
FX_HIGH      = 12.50
# FX threshold for release routing:
#   FX > FX_THRESHOLD (cedi weak)  -> sell on international market
#   FX <= FX_THRESHOLD             -> transfer to BoG national reserve
FX_THRESHOLD = 11.00

# ASM weekly volume: U[V_MIN, V_MAX] kg/week
V_MIN = 2_000.0
V_MAX = 3_000.0

# Annual procurement target (GANRAP mandate)
Q_ANNUAL = 127_000.0

# Supply ratio
RHO   = 0.99242
R_MIN = 0.0
S_BAR = 3_000.0

# Objective weights — from 2025 sensitivity analysis
# Best overall: 97.4% improvement vs historical
ALPHA = 3.861  # under-release penalty
BETA  = 2.240  # over-release penalty
GAMMA = 0.164  # intermediate inventory reward
PHI   = 5.0    # annual shortfall penalty (GANRAP mandate applies)

# Scenarios
NUM_SCENARIOS = 20
np.random.seed(42)

# DP grid
INV_GRID_POINTS = 300
X_GRID_POINTS   = 30
Y_GRID_POINTS   = 30

# ─────────────────────────────────────────────────────────────
# SECTION 1 — Build baselines
# ─────────────────────────────────────────────────────────────

# JP Morgan 2026 weekly gold price series
# Linearly interpolated between quarterly forecasts
gold_weekly = []
for q in range(4):
    start = JP_QUARTERLY[q]
    end   = JP_QUARTERLY[q + 1] if q < 3 else JP_QUARTERLY[q]
    for w in range(13):
        gold_weekly.append(start + (end - start) * w / 13)
gold_weekly = np.array(gold_weekly[:T])

# Mid-point exchange rate for deterministic baseline
fx_mid = (FX_LOW + FX_HIGH) / 2   # 11.50 GHS/USD

# Period-specific lambda: buy cost per kg using mid-point FX
# lambda_t = (gold_t * fx_mid * C_TROY) / K_CONV
lambda_arr  = gold_weekly * fx_mid * C_TROY / K_CONV   # (T,) array
lambda_mean = float(lambda_arr.mean())

# p_sell = lambda (Option A: buy cost as proxy for transfer price)
p_sell_arr  = lambda_arr.copy()   # (T,) same as lambda for 2026
p_sell_mean = float(p_sell_arr.mean())

print("=" * 65)
print("GoldBod Stochastic DP — 2026 Forward Schedule")
print("=" * 65)
print(f"  Gold (USD/oz) : Q1 ${JP_QUARTERLY[0]:,}  "
      f"Q2 ${JP_QUARTERLY[1]:,}  "
      f"Q3 ${JP_QUARTERLY[2]:,}  "
      f"Q4 ${JP_QUARTERLY[3]:,}")
print(f"  Gold range    : {gold_weekly.min():,.0f} – "
      f"{gold_weekly.max():,.0f} USD/oz")
print(f"  FX range      : U[{FX_LOW}, {FX_HIGH}] GHS/USD  "
      f"(mid = {fx_mid:.2f})")
print(f"  FX threshold  : {FX_THRESHOLD} GHS/USD  "
      f"(above -> market; at/below -> BoG reserve)")
print(f"  ASM volume    : U[{V_MIN:,.0f}, {V_MAX:,.0f}] kg/week")
print(f"  Q_ANNUAL      : {Q_ANNUAL:,.0f} kg  (GANRAP mandate)")
print(f"  lambda mean   : GHS {lambda_mean:,.2f}/kg  (period-specific)")
print(f"  p_sell mean   : GHS {p_sell_mean:,.2f}/kg  "
      f"(= lambda, Option A proxy)")
print(f"  rho           : {RHO}  (0.758% service charge)")
print(f"  S_BAR         : {S_BAR:,.0f} kg  (working buffer cap)")
print(f"  alpha/beta/gamma/phi: {ALPHA}/{BETA}/{GAMMA}/{PHI}")
print(f"  T = {T} weekly periods")
print("=" * 65 + "\n")

# ─────────────────────────────────────────────────────────────
# SECTION 2 — Scenario generation
# ─────────────────────────────────────────────────────────────

def generate_scenarios():
    """
    Per scenario xi and period t draw independently:
      r_t^(xi) ~ U[FX_LOW, FX_HIGH]   exchange rate
      V_t^(xi) ~ U[V_MIN,  V_MAX]     ASM availability (kg)

    Derived quantities per scenario:
      lambda_t^(xi) = (gold_t * r_t^(xi) * C_TROY) / K_CONV
      I_t^(xi)      = lambda_t^(xi) * V_t^(xi)
      E_t^(xi)      = RHO * I_t^(xi)

    Gold price fixed at JP Morgan 2026 forecasts.
    p_sell = lambda (Option A).
    """
    n    = NUM_SCENARIOS
    fx   = np.random.uniform(FX_LOW, FX_HIGH, (n, T))
    vol  = np.random.uniform(V_MIN,  V_MAX,   (n, T))

    # CORRECTED: (gold * fx * C_TROY) / K_CONV
    cost   = gold_weekly[None, :] * fx * C_TROY / K_CONV
    inflow = cost * vol
    target = RHO * inflow
    probs  = np.ones(n) / n

    print(f"Scenarios ({n}, seed=42):")
    print(f"  FX range   : [{fx.min():.2f}, {fx.max():.2f}] GHS/USD")
    print(f"  Vol range  : [{vol.min():,.0f}, {vol.max():,.0f}] kg/week")
    print(f"  lambda range: GHS {cost.min():,.2f} – {cost.max():,.2f}/kg")
    print(f"  E_t range  : GHS {target.min()/1e9:.3f}bn – "
          f"{target.max()/1e9:.3f}bn/week\n")

    return cost, vol, fx, inflow, target, probs

# ─────────────────────────────────────────────────────────────
# SECTION 3 — DP solver
# ─────────────────────────────────────────────────────────────

def _run_single_dp(cost_xi, vol_xi, target_xi,
                   lambda_xi, lambda_mean_xi, p_sell_xi):
    """
    Parameters:
      lambda_xi      : (T,) period-specific buy cost for this scenario
      lambda_mean_xi : scalar mean buy cost for this scenario
      p_sell_xi      : (T,) transfer price for this scenario
                       (= lambda_xi for Option A)

    Terminal condition: -lambda_mean_xi * s_T
    Inventory reward:   -GAMMA * lambda_mean_xi * s_next
    Discrepancy:        E_t - p_sell_xi[t] * y_t
    Shortfall penalty:  PHI * lambda_mean_xi * shortfall (in forward sim)
    """
    inv_grid = np.linspace(0, S_BAR, INV_GRID_POINTS)
    n_inv    = len(inv_grid)
    V_dp     = np.full((T + 1, n_inv), np.inf)
    policy_x = np.zeros((T, n_inv))
    policy_y = np.zeros((T, n_inv))

    # Terminal condition
    for i, sv in enumerate(inv_grid):
        if sv >= R_MIN:
            V_dp[T][i] = -lambda_mean_xi * sv

    # Backward pass
    for t in reversed(range(T)):
        Et_xi    = target_xi[t]
        vol_t    = vol_xi[t]
        p_sell_t = p_sell_xi[t]   # period-specific transfer price
        x_grid   = np.linspace(0, vol_t, X_GRID_POINTS)

        for i, s_prev in enumerate(inv_grid):
            best_val = np.inf
            best_x   = 0.0
            best_y   = 0.0

            for xv in x_grid:
                avail  = s_prev + xv
                y_grid = np.linspace(0, min(avail, S_BAR),
                                     Y_GRID_POINTS)
                for yv in y_grid:
                    s_next = float(np.clip(avail - yv, 0.0, S_BAR))
                    j = min(int(round(s_next / S_BAR * (n_inv - 1))),
                            n_inv - 1)
                    if V_dp[t + 1][j] == np.inf:
                        continue

                    disc    = Et_xi - p_sell_t * yv
                    d_plus  = max(disc,  0.0)   # under-release
                    d_minus = max(-disc, 0.0)   # over-release

                    val = (ALPHA * d_plus + BETA * d_minus
                           - GAMMA * lambda_mean_xi * s_next
                           + V_dp[t + 1][j])
                    if val < best_val:
                        best_val = val
                        best_x   = xv
                        best_y   = yv

            V_dp[t][i]     = best_val if best_val < np.inf else np.inf
            policy_x[t][i] = best_x
            policy_y[t][i] = best_y

    obj    = V_dp[0][0]
    status = 'Optimal' if obj < np.inf else 'Infeasible'
    return V_dp, policy_x, policy_y, status, obj

# ─────────────────────────────────────────────────────────────
# SECTION 4 — Forward simulation
# ─────────────────────────────────────────────────────────────

def _simulate_forward(policy_x, policy_y, vol_xi, fx_xi,
                      target_xi, p_sell_xi, lambda_mean_xi):
    inv_grid  = np.linspace(0, S_BAR, INV_GRID_POINTS)
    n_inv     = len(inv_grid)
    s         = S0
    cum_purch = 0.0
    traj = {k: [] for k in [
        'inventory', 'purchase', 'release',
        'release_bog', 'release_market',
        'discrepancy', 'over_supply', 'under_supply',
        'cum_purchase']}

    for t in range(T):
        Et_xi = target_xi[t]
        vol_t = vol_xi[t]
        fx_t  = fx_xi[t]

        i      = min(int(round(s / S_BAR * (n_inv - 1))), n_inv - 1)
        x_pol  = float(np.clip(policy_x[t][i], 0.0, vol_t))
        avail  = s + x_pol
        y_pol  = float(np.clip(policy_y[t][i], 0.0, avail))
        s_next = float(np.clip(avail - y_pol, 0.0, S_BAR))
        cum_purch += x_pol

        # FX-threshold release routing
        if fx_t > FX_THRESHOLD:
            y_market = y_pol
            y_bog    = 0.0
        else:
            y_bog    = y_pol
            y_market = 0.0

        disc = Et_xi - p_sell_xi[t] * y_pol
        traj['inventory'].append(s_next)
        traj['purchase'].append(x_pol)
        traj['release'].append(y_pol)
        traj['release_bog'].append(y_bog)
        traj['release_market'].append(y_market)
        traj['discrepancy'].append(disc)
        traj['over_supply'].append(max(disc,  0.0))
        traj['under_supply'].append(max(-disc, 0.0))
        traj['cum_purchase'].append(cum_purch)
        s = s_next

    # Annual shortfall penalty (GANRAP mandate applies for 2026)
    shortfall_kg          = max(Q_ANNUAL - cum_purch, 0.0)
    traj['shortfall_kg']  = shortfall_kg
    traj['shortfall_ghs'] = PHI * lambda_mean_xi * shortfall_kg
    traj['final_inv']     = s
    return traj

# ─────────────────────────────────────────────────────────────
# SECTION 5 — Stochastic DP (scenario decomposition)
# ─────────────────────────────────────────────────────────────

def solve_stochastic_dp(cost_scen, vol_scen, fx_scen,
                        inflow_scen, target_scen, probs):
    n_scen = len(probs)
    t0     = time.time()
    all_V  = []; all_px = []; all_py = []
    all_traj = []; results = []

    print(f"Solving {n_scen} scenarios (purchase + release)...")
    print(f"{'Scen':>5}  {'Status':>10}  {'Obj (GHS)':>20}  "
          f"{'Purch (kg)':>12}  {'Shortfall':>10}  {'Yr-end Inv':>12}")
    print("-" * 80)

    for xi in range(n_scen):
        # Scenario-specific lambda: JP Morgan price * scenario FX
        lambda_xi      = gold_weekly * fx_scen[xi] * C_TROY / K_CONV
        lambda_mean_xi = float(lambda_xi.mean())
        # Option A: p_sell = lambda (buy cost proxy)
        p_sell_xi      = lambda_xi.copy()

        V_dp, px, py, status_xi, obj_xi = _run_single_dp(
            cost_scen[xi], vol_scen[xi], target_scen[xi],
            lambda_xi, lambda_mean_xi, p_sell_xi)
        traj_xi = _simulate_forward(
            px, py, vol_scen[xi], fx_scen[xi],
            target_scen[xi], p_sell_xi, lambda_mean_xi)

        all_V.append(V_dp); all_px.append(px); all_py.append(py)
        all_traj.append(traj_xi)

        print(f"  {xi:>3d}  {status_xi:>10}  "
              f"{obj_xi:>20,.0f}  "
              f"{sum(traj_xi['purchase']):>12,.1f}  "
              f"{traj_xi['shortfall_kg']:>10,.1f}  "
              f"{traj_xi['final_inv']:>12,.1f}")

        disc_arr = (np.array(traj_xi['over_supply'])
                    + np.array(traj_xi['under_supply']))
        results.append({
            'Scenario':               xi,
            'Status':                 status_xi,
            'Yearend_Inventory_kg':   traj_xi['final_inv'],
            'Total_Purchase_kg':      sum(traj_xi['purchase']),
            'Total_Release_kg':       sum(traj_xi['release']),
            'Total_Release_BOG_kg':   sum(traj_xi['release_bog']),
            'Total_Release_Market_kg':sum(traj_xi['release_market']),
            'Shortfall_kg':           traj_xi['shortfall_kg'],
            'Shortfall_GHS':          traj_xi['shortfall_ghs'],
            'Total_Abs_Disc_GHS':     disc_arr.sum(),
            'Objective_GHS':          obj_xi,
            'Over_Supply_Periods':
                sum(1 for v in traj_xi['over_supply']  if v > 0),
            'Under_Supply_Periods':
                sum(1 for v in traj_xi['under_supply'] if v > 0),
        })

    solve_time = time.time() - t0
    df_scen    = pd.DataFrame(results)
    n_opt      = int((df_scen['Status'] == 'Optimal').sum())
    n_inf      = int(n_scen - n_opt)

    w           = probs
    inv_all     = np.array([t['inventory']      for t in all_traj])
    purch_all   = np.array([t['purchase']       for t in all_traj])
    release_all = np.array([t['release']        for t in all_traj])
    rel_bog_all = np.array([t['release_bog']    for t in all_traj])
    rel_mkt_all = np.array([t['release_market'] for t in all_traj])
    disc_all    = np.array([t['discrepancy']    for t in all_traj])
    cum_all     = np.array([t['cum_purchase']   for t in all_traj])

    inv_mean     = np.average(inv_all,     axis=0, weights=w)
    purch_mean   = np.average(purch_all,   axis=0, weights=w)
    release_mean = np.average(release_all, axis=0, weights=w)
    rel_bog_mean = np.average(rel_bog_all, axis=0, weights=w)
    rel_mkt_mean = np.average(rel_mkt_all, axis=0, weights=w)
    disc_mean    = np.average(disc_all,    axis=0, weights=w)
    cum_mean     = np.average(cum_all,     axis=0, weights=w)
    fx_mean      = np.average(fx_scen,     axis=0, weights=w)

    exp_obj = sum(probs[xi] * all_V[xi][0][0]
                  for xi in range(n_scen)
                  if all_V[xi][0][0] < np.inf)

    print(f"\nAll {n_scen} scenarios complete in {solve_time:.2f}s")
    print(f"Overall: {n_opt}/{n_scen} Optimal, {n_inf}/{n_scen} Infeasible\n")
    print("=" * 65)
    print("AGGREGATE RESULTS — GoldBod Stochastic DP (2026 Forward)")
    print("=" * 65)
    print(f"  Expected Objective (GHS)    : {exp_obj:>22,.0f}")
    print(f"  Mean Year-end Inventory (kg): "
          f"{df_scen['Yearend_Inventory_kg'].mean():>22,.1f}  "
          f"(Std: {df_scen['Yearend_Inventory_kg'].std():,.1f})")
    print(f"  Mean Total Purchase (kg)    : "
          f"{df_scen['Total_Purchase_kg'].mean():>22,.1f}  "
          f"[Q = {Q_ANNUAL:,.0f}]")
    print(f"  Mean Total Release (kg)     : "
          f"{df_scen['Total_Release_kg'].mean():>22,.1f}")
    print(f"    -> To BoG reserve (kg)    : "
          f"{df_scen['Total_Release_BOG_kg'].mean():>22,.1f}")
    print(f"    -> To market (kg)         : "
          f"{df_scen['Total_Release_Market_kg'].mean():>22,.1f}")
    print(f"  Mean Shortfall (kg)         : "
          f"{df_scen['Shortfall_kg'].mean():>22,.1f}  "
          f"(Std: {df_scen['Shortfall_kg'].std():,.1f})")
    print(f"  Scenarios meeting Q         : "
          f"{int((df_scen['Shortfall_kg']==0).sum()):>22d} / {n_scen}")
    print(f"  Mean Total Disc (GHS)       : "
          f"{df_scen['Total_Abs_Disc_GHS'].mean():>22,.0f}  "
          f"(Std: {df_scen['Total_Abs_Disc_GHS'].std():,.0f})")
    print(f"  Over-supply periods (avg)   : "
          f"{df_scen['Over_Supply_Periods'].mean():>22.1f}")
    print(f"  Under-supply periods (avg)  : "
          f"{df_scen['Under_Supply_Periods'].mean():>22.1f}")
    print(f"  Solve time (s)              : {solve_time:>22.2f}")
    print("=" * 65 + "\n")

    return {
        'exp_obj':      exp_obj,       'solve_time':    solve_time,
        'inv_mean':     inv_mean,      'purch_mean':    purch_mean,
        'release_mean': release_mean,  'rel_bog_mean':  rel_bog_mean,
        'rel_mkt_mean': rel_mkt_mean,  'disc_mean':     disc_mean,
        'cum_mean':     cum_mean,      'fx_mean':       fx_mean,
        'inv_all':      inv_all,       'purch_all':     purch_all,
        'release_all':  release_all,   'rel_bog_all':   rel_bog_all,
        'rel_mkt_all':  rel_mkt_all,   'df_scen':       df_scen,
        'all_V':        all_V,         'all_px':        all_px,
        'all_py':       all_py,        'lambda_mean':   lambda_mean,
        'lambda_arr':   lambda_arr,    'n_opt':         n_opt,
        'n_inf':        n_inf,
    }

# ─────────────────────────────────────────────────────────────
# SECTION 6 — Save results
# ─────────────────────────────────────────────────────────────

def save_results(res):
    pd.DataFrame({
        'Period':                list(periods),
        'Avg_Purchase_kg':       res['purch_mean'].tolist(),
        'Avg_Release_kg':        res['release_mean'].tolist(),
        'Avg_Release_BOG_kg':    res['rel_bog_mean'].tolist(),
        'Avg_Release_Market_kg': res['rel_mkt_mean'].tolist(),
        'Avg_Inventory_kg':      res['inv_mean'].tolist(),
        'Avg_CumPurchase_kg':    res['cum_mean'].tolist(),
        'Avg_FX_GHSUSD':         res['fx_mean'].tolist(),
        'Avg_Discrepancy_GHS':   res['disc_mean'].tolist(),
        'Gold_Price_USD':        gold_weekly.tolist(),
        'Lambda_Arr_GHS_kg':     lambda_arr.tolist(),
    }).to_csv(OUTPUT_DIR + 'dp_2026_results_table.csv', index=False)

    res['df_scen'].to_csv(
        OUTPUT_DIR + 'dp_2026_scenario_summary.csv', index=False)

    df_inv = pd.DataFrame(
        res['inv_all'].T,
        columns=[f'Scenario_{i}' for i in range(NUM_SCENARIOS)])
    df_inv.insert(0, 'Period', list(periods))
    df_inv.to_csv(
        OUTPUT_DIR + 'dp_2026_inventory_all_scenarios.csv', index=False)

    df_s = res['df_scen']
    pd.DataFrame.from_dict({
        'Expected_Objective_GHS':       res['exp_obj'],
        'Mean_Yearend_Inventory_kg':    df_s['Yearend_Inventory_kg'].mean(),
        'Std_Yearend_Inventory_kg':     df_s['Yearend_Inventory_kg'].std(),
        'Mean_Total_Purchase_kg':       df_s['Total_Purchase_kg'].mean(),
        'Std_Total_Purchase_kg':        df_s['Total_Purchase_kg'].std(),
        'Mean_Total_Release_kg':        df_s['Total_Release_kg'].mean(),
        'Mean_Total_Release_BOG_kg':    df_s['Total_Release_BOG_kg'].mean(),
        'Mean_Total_Release_Market_kg': df_s['Total_Release_Market_kg'].mean(),
        'Mean_Shortfall_kg':            df_s['Shortfall_kg'].mean(),
        'Std_Shortfall_kg':             df_s['Shortfall_kg'].std(),
        'Scenarios_Meeting_Q':          int((df_s['Shortfall_kg']==0).sum()),
        'Mean_Total_Disc_GHS':          df_s['Total_Abs_Disc_GHS'].mean(),
        'Std_Total_Disc_GHS':           df_s['Total_Abs_Disc_GHS'].std(),
        'Mean_Over_Supply_Periods':     df_s['Over_Supply_Periods'].mean(),
        'Mean_Under_Supply_Periods':    df_s['Under_Supply_Periods'].mean(),
        'N_Optimal_Scenarios':          res['n_opt'],
        'N_Infeasible_Scenarios':       res['n_inf'],
        'Solve_Time_s':                 res['solve_time'],
    }, orient='index', columns=['Value']
    ).to_csv(OUTPUT_DIR + 'dp_2026_aggregate_stats.csv')

    print("Saved: dp_2026_aggregate_stats.csv")
    print("Saved: dp_2026_scenario_summary.csv")
    print("Saved: dp_2026_inventory_all_scenarios.csv")
    print("Saved: dp_2026_results_table.csv\n")

# ─────────────────────────────────────────────────────────────
# SECTION 7 — Visualisations
# ─────────────────────────────────────────────────────────────

C1='#1f77b4'; C2='#d62728'; C3='#2ca02c'; C4='#ff7f0e'

def plot_trajectory(res):
    fig, axes = plt.subplots(4, 1, figsize=(14, 17), facecolor='white')
    t_ax = list(periods)
    inv_all = res['inv_all']

    # Inventory fan
    ax = axes[0]
    ax.fill_between(t_ax, inv_all.min(0), inv_all.max(0),
                    alpha=0.12, color=C2, label='Scenario range')
    ax.fill_between(t_ax,
                    np.percentile(inv_all, 25, 0),
                    np.percentile(inv_all, 75, 0),
                    alpha=0.25, color=C2, label='IQR')
    ax.plot(t_ax, res['inv_mean'], color=C2, lw=2.2,
            label='Mean inventory', marker='o', ms=2.5)
    ax.axhline(S_BAR, color='grey', lw=1.0, ls=':',
               label=f'S_BAR ({S_BAR:,.0f} kg)')
    ax.set_title('GoldBod Inventory Buffer — 2026 Forward Schedule',
                 fontsize=12, fontweight='bold')
    ax.set_ylabel('Inventory (kg)')
    ax.legend(ncol=3, fontsize=8); ax.grid(True, alpha=0.3)

    # Cumulative purchase vs Q
    ax2 = axes[1]
    cum_scen = np.array([
        np.cumsum(res['purch_all'][xi]) for xi in range(NUM_SCENARIOS)])
    ax2.plot(t_ax, res['cum_mean'], color=C1, lw=2.2,
             label='Mean cumulative purchase (kg)')
    ax2.fill_between(t_ax, cum_scen.min(0), cum_scen.max(0),
                     alpha=0.10, color=C1)
    ax2.axhline(Q_ANNUAL, color='red', lw=1.8, ls='--',
                label=f'Q_ANNUAL = {Q_ANNUAL:,.0f} kg (GANRAP)')
    ax2.set_title('Cumulative Purchases vs GANRAP Annual Target',
                  fontsize=12, fontweight='bold')
    ax2.set_ylabel('Cumulative Purchase (kg)')
    ax2.legend(fontsize=9); ax2.grid(True, alpha=0.3)

    # Weekly purchase and release
    ax3 = axes[2]
    ax3.bar(t_ax, res['purch_mean'], color=C1, alpha=0.75,
            width=0.7, label='Mean purchase x_t (kg)')
    ax3.bar(t_ax, res['release_mean'], color=C4, alpha=0.6,
            width=0.7, label='Mean release y_t (kg)')
    ax3.axhline(V_MIN, color='orange', lw=1.3, ls='--',
                label=f'V_min = {V_MIN:,.0f} kg/week')
    ax3.set_title('Weekly Purchase and Release Decisions',
                  fontsize=12, fontweight='bold')
    ax3.set_ylabel('kg/week')
    ax3.legend(fontsize=8); ax3.grid(True, alpha=0.3, axis='y')

    # Discrepancy + gold price
    ax4 = axes[3]; ax4b = ax4.twinx()
    ax4.plot(t_ax, res['disc_mean'], color=C3, lw=2.0,
             marker='s', ms=3, label='Mean discrepancy (GHS)')
    ax4b.plot(t_ax, gold_weekly, color='goldenrod', lw=1.5,
              ls='--', label='JP Morgan 2026 gold (USD/oz)')
    ax4.axhline(0, color='black', lw=0.8, ls=':')
    ax4.set_title('Mean Supply Discrepancy & Gold Price',
                  fontsize=12, fontweight='bold')
    ax4.set_xlabel('Week')
    ax4.set_ylabel('Discrepancy (GHS)', color=C3)
    ax4b.set_ylabel('Gold Price (USD/oz)', color='goldenrod')
    lines  = ax4.get_legend_handles_labels()
    lines2 = ax4b.get_legend_handles_labels()
    ax4.legend(lines[0]+lines2[0], lines[1]+lines2[1], fontsize=8)
    ax4.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(OUTPUT_DIR + 'dp_2026_trajectory.png', dpi=200,
                bbox_inches='tight', facecolor='white')
    plt.show(); print("Saved: dp_2026_trajectory.png")


def plot_policy_map(res):
    avg_px = np.mean(res['all_px'], axis=0)
    avg_py = np.mean(res['all_py'], axis=0)
    fig, axes = plt.subplots(1, 2, figsize=(16, 5), facecolor='white')
    for ax, data, title, label in [
        (axes[0], avg_px, 'Optimal Purchase Policy x*(t,s)',
         'Purchase x* (kg)'),
        (axes[1], avg_py, 'Optimal Release Policy y*(t,s)',
         'Release y* (kg)'),
    ]:
        im = ax.imshow(data.T, aspect='auto', origin='lower',
                       cmap='Blues',
                       extent=[-0.5, T-0.5, 0, S_BAR])
        plt.colorbar(im, ax=ax, label=label)
        ax.set_title(title, fontsize=11, fontweight='bold')
        ax.set_xlabel('Week t')
        ax.set_ylabel('Inventory State s (kg)')
    plt.suptitle('Average Optimal Policy Maps — 2026 Forward Schedule',
                 fontsize=12, fontweight='bold')
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR + 'dp_2026_policy_map.png', dpi=180,
                bbox_inches='tight', facecolor='white')
    plt.show(); print("Saved: dp_2026_policy_map.png")


def plot_value_function(res):
    inv_grid = np.linspace(0, S_BAR, INV_GRID_POINTS)
    V_avg    = np.mean(res['all_V'], axis=0)
    V_plot   = np.where(V_avg == np.inf, np.nan, V_avg)
    fig, ax  = plt.subplots(figsize=(14, 5), facecolor='white')
    im = ax.contourf(range(T+1), inv_grid, V_plot.T,
                     levels=30, cmap='RdYlGn')
    plt.colorbar(im, ax=ax, label='V_t(s) [GHS]')
    ax.set_title('Average Value Function — 2026 Forward Schedule',
                 fontsize=12, fontweight='bold')
    ax.set_xlabel('Week t'); ax.set_ylabel('Inventory s (kg)')
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR + 'dp_2026_value_function.png', dpi=180,
                bbox_inches='tight', facecolor='white')
    plt.show(); print("Saved: dp_2026_value_function.png")


def plot_distributions(res):
    df_s = res['df_scen']
    fig, axes = plt.subplots(2, 2, figsize=(14, 9), facecolor='white')
    panels = [
        (df_s['Yearend_Inventory_kg'], 'Year-end Inventory (kg)',
         axes[0,0], C1),
        (df_s['Shortfall_kg'],         'Annual Shortfall vs Q (kg)',
         axes[0,1], C2),
        (df_s['Total_Release_kg'],     'Total Release (kg)',
         axes[1,0], C4),
        (df_s['Total_Purchase_kg'],    'Total Purchase (kg)',
         axes[1,1], C1),
    ]
    for vals, xlabel, ax, color in panels:
        ax.hist(vals, bins=8, color=color, alpha=0.78,
                edgecolor='white')
        ax.axvline(vals.mean(), color='black', lw=2, ls='--',
                   label=f'Mean: {vals.mean():,.0f}')
        if vals.std() > 0:
            ax.axvline(vals.mean()+vals.std(), color='grey',
                       lw=1.2, ls=':',
                       label=f'±1SD: {vals.std():,.0f}')
            ax.axvline(vals.mean()-vals.std(), color='grey',
                       lw=1.2, ls=':')
        ax.set_xlabel(xlabel, fontsize=9)
        ax.set_ylabel('Frequency')
        ax.legend(fontsize=8); ax.grid(True, alpha=0.3)
    plt.suptitle(
        f'Outcome Distributions — {NUM_SCENARIOS} Scenarios\n'
        f'JP Morgan 2026, FX~U[{FX_LOW},{FX_HIGH}], '
        f'Vol~U[{V_MIN:.0f},{V_MAX:.0f}] kg/week',
        fontsize=11, fontweight='bold')
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR + 'dp_2026_distributions.png', dpi=180,
                bbox_inches='tight', facecolor='white')
    plt.show(); print("Saved: dp_2026_distributions.png")


def plot_dashboard(res):
    fig = plt.figure(figsize=(16, 10), facecolor='white')
    gs  = gridspec.GridSpec(2, 3, figure=fig,
                            hspace=0.45, wspace=0.38)
    t_ax = list(periods); df_s = res['df_scen']

    kpis = [
        ('Mean Year-end Inventory (kg)',
         df_s['Yearend_Inventory_kg'].mean(), C1),
        ('Scenarios Meeting Q = 127,000 kg',
         float((df_s['Shortfall_kg']==0).sum()), C3),
        ('Mean Annual Shortfall (kg)',
         df_s['Shortfall_kg'].mean(), C2),
    ]
    for idx, (title, val, col) in enumerate(kpis):
        ax = fig.add_subplot(gs[0, idx])
        ax.bar([''], [val], color=col, alpha=0.8, width=0.4)
        ax.text(0, val*1.02 if val > 0 else 0.1,
                f'{val:,.1f}', ha='center', va='bottom', fontsize=9)
        ax.set_title(title, fontsize=9, fontweight='bold')
        ax.grid(True, alpha=0.3, axis='y')

    ax4 = fig.add_subplot(gs[1, 0])
    ax4.plot(t_ax, gold_weekly, color='goldenrod', lw=2)
    ax4.set_title('JP Morgan 2026 Gold Price (USD/oz)',
                  fontsize=10, fontweight='bold')
    ax4.set_xlabel('Week'); ax4.set_ylabel('USD/oz')
    ax4.grid(True, alpha=0.3)

    ax5 = fig.add_subplot(gs[1, 1])
    ax5.plot(t_ax, res['cum_mean'], color=C1, lw=2,
             label='Mean cumulative purchase')
    ax5.axhline(Q_ANNUAL, color='red', lw=1.5, ls='--',
                label=f'Q = {Q_ANNUAL:,.0f} kg')
    ax5.set_title('Cumulative Purchase vs Annual Target',
                  fontsize=10, fontweight='bold')
    ax5.set_xlabel('Week'); ax5.set_ylabel('kg')
    ax5.legend(fontsize=8); ax5.grid(True, alpha=0.3)

    ax6 = fig.add_subplot(gs[1, 2])
    inv_all = res['inv_all']
    ax6.fill_between(t_ax, inv_all.min(0), inv_all.max(0),
                     alpha=0.12, color=C2)
    ax6.fill_between(t_ax,
                     np.percentile(inv_all, 25, 0),
                     np.percentile(inv_all, 75, 0),
                     alpha=0.25, color=C2, label='IQR')
    ax6.plot(t_ax, res['inv_mean'], color=C2, lw=2,
             label='Mean inventory')
    ax6.axhline(S_BAR, color='grey', lw=1.2, ls=':',
                label=f'S_BAR ({S_BAR:,.0f} kg)')
    ax6.set_title('Inventory Fan', fontsize=10, fontweight='bold')
    ax6.set_xlabel('Week'); ax6.set_ylabel('kg')
    ax6.legend(fontsize=7); ax6.grid(True, alpha=0.3)

    fig.suptitle(
        f'GoldBod DP Dashboard — 2026 Forward Schedule\n'
        f'JP Morgan: Q1 ${JP_QUARTERLY[0]:,} → Q4 ${JP_QUARTERLY[3]:,} USD/oz  |  '
        f'FX~U[{FX_LOW},{FX_HIGH}]  |  '
        f'α={ALPHA}, β={BETA}, γ={GAMMA}',
        fontsize=11, fontweight='bold', y=1.01)
    plt.savefig(OUTPUT_DIR + 'dp_2026_dashboard.png', dpi=200,
                bbox_inches='tight', facecolor='white')
    plt.show(); print("Saved: dp_2026_dashboard.png")


# ─────────────────────────────────────────────────────────────
# SECTION 8 — Main
# ─────────────────────────────────────────────────────────────

if __name__ == '__main__':
    cost_scen, vol_scen, fx_scen, inflow_scen, target_scen, probs = \
        generate_scenarios()

    res = solve_stochastic_dp(
        cost_scen, vol_scen, fx_scen,
        inflow_scen, target_scen, probs)

    save_results(res)

    print("Generating figures...")
    plot_trajectory(res)
    plot_policy_map(res)
    plot_value_function(res)
    plot_distributions(res)
    plot_dashboard(res)

    print("\n" + "=" * 65)
    print("GoldBod Stochastic DP — 2026 Forward Schedule Complete.")
    print("=" * 65)